kind: pipeline
name: DroneCoreCoreMaster
type: docker

steps:
  - name: test'n'deploy
    image: maven:3.8.5-eclipse-temurin-16
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml
      - mvn deploy -DskipTests=true -B -s workflow_settings.xml
      - mvn deploy -DskipTests=true -B -f pom-for-api.xml -s workflow_settings.xml

trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
name: DroneCoreCore
type: docker

steps:
  - name: test
    image: maven:3.8.5-eclipse-temurin-16
    environment:
      NRM_PW:
        from_secret: NEXUS_DEV_PWD
    commands:
      - mvn install -DskipTests=true -B -V -s workflow_settings.xml

trigger:
  event:
    - push