name: GalaxyCoreCore
version: ${project.version}
main: net.galaxycore.galaxycorecore.GalaxyCoreCore
api-version: 1.16
authors: [ Bloekchengrafik ]

depend:
  - LuckPerms

commands:
  chattools:
    description: Open the Chattools on a specific Message
    usage: /chattools [messageid]
